[settings]
# use uv for venv management when uv.lock is present
python.uv_venv_auto = true
# auto-trust mise.toml in these directories
trusted_config_paths = [
  "~/Developer/projex",
  "~/Developer/marta",
]
idiomatic_version_file_enable_tools = ["ruby", "node"]

[tools]
node = "lts"
ruby = "3.3"
python = "3.13"
java = "zulu-17"  # react native requires jdk 17
cocoapods = "1.16.2"
