[general]
import = [
  "~/.config/alacritty/themes/ayu_mirage.toml"
]

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt",     chars = "\u001bB"   },
  { key = "Right", mods = "Alt",     chars = "\u001bF"   },
  { key = "Left",  mods = "Command", chars = "\u001bOH"  },
  { key = "Right", mods = "Command", chars =  "\u001bOF" },
  { key = "Back",  mods = "Command", chars = "\u0015"    },
]

[window]
option_as_alt = "Both"
decorations = "None"
dynamic_padding = true
opacity = 1.0

[font]
size = 13
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
